config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                 new_user_confirmation GET    /users/confirmation/new(.:format)                                                        devise/confirmations#new
#                     user_confirmation GET    /users/confirmation(.:format)                                                            devise/confirmations#show
#                                       POST   /users/confirmation(.:format)                                                            devise/confirmations#create
#                       new_user_unlock GET    /users/unlock/new(.:format)                                                              devise/unlocks#new
#                           user_unlock GET    /users/unlock(.:format)                                                                  devise/unlocks#show
#                                       POST   /users/unlock(.:format)                                                                  devise/unlocks#create
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: 'gifts#index'

  devise_for :users

  resources :gifts

  get 'my_gifts', to: 'gifts#my'
end

app/models/gift.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: gifts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_gifts_on_title  (title)
#
class Gift < ApplicationRecord
  has_many :giftings, dependent: :destroy
  has_many :users, through: :giftings
  has_many :occasions, through: :giftings
  has_many :recipients, through: :giftings

  validates :title, presence: true
end

app/controllers/gifts_controller.rb
# frozen_string_literal: true

class GiftsController < ApplicationController
  before_action :authenticate_user!

  def index
    @giftings = GiftContainer[:filter].call(params).page(params[:page])

    @occasions = Occasion.pluck(:title)
    @recipients = Recipient.pluck(:title)
  end

  def new
    @gift = Gift.new
    @occasions = Occasion.pluck(:title, :id)
    @recipients = Recipient.pluck(:title, :id)
  end

  def edit
    @gift = current_user.gifts.find(params[:id])
    @occasions = Occasion.pluck(:title, :id)
    @recipients = Recipient.pluck(:title, :id)
  end

  def create
    creating = GiftContainer[:create].call(gift_params, current_user.id)

    if creating.success?
      redirect_to gifts_path, notice: 'Gift created!'
    else
      redirect_to gifts_path, alert: 'Something went wrong'
    end
  end

  def update
    update = GiftContainer[:update].call(params[:id], gift_params, current_user.id)

    if update.success?
      redirect_to my_gifts_path, notice: 'Gift successfully updated'
    else
      redirect_to my_gifts_path, notice: update.failure
    end
  end

  def destroy
    @gift = current_user.gifts.find(params[:id])

    if @gift.destroy
      redirect_to my_gifts_path, notice: 'Gift successfully deleted'
    else
      redirect_to my_gifts_path, alert: 'Something went wrong'
    end
  end

  # User's gifts
  def my
    @giftings =
      Gifting.includes(:gift, :recipient).where(user_id: current_user.id).page(params[:page])
  end

  private

  def gift_params
    params.require(:gift).permit(:title, :occasion_id, :recipient_id)
  end
end

app/helpers/gifts_helper.rb
# frozen_string_literal: true

module GiftsHelper
end

app/views/gifts/_filters.html.slim
.card
  .card-body
    = form_with url: root_path, method: :get, remote: false do
      .row
        .col-12
          => label_tag :recipient, t('.to_whom')
          = select_tag :recipient, options_for_select(@recipients, params[:recipient]),
            class: 'form-control', include_blank: true
      .row
        .col-12
          => label_tag :occasion, t('.which_occasion')
          = select_tag :occasion, options_for_select(@occasions, params[:occasion]),
            class: 'form-control', include_blank: true

      .col-12.text-center.mt-4
        = submit_tag t('.find'), class: 'btn btn-success'

app/views/gifts/_form.html.slim
.row
  .col-6
    = form_with model: @gift do |f|
      p
        => f.label :title, t('.what')
        = f.text_field :title, class: 'form-control', required: true

      p
        => f.label :recipient_id, t('.to_whom')
        => f.select :recipient_id, @recipients, {}, class: 'form-control'

      p
        => f.label :occasion_id, t('.which_occasion')
        = f.select :occasion_id, @occasions, {}, class: 'form-control'

      p
        = f.submit 'Вот я молодец!', class: 'btn btn-success'

app/views/gifts/_list.html.slim
ul.list-group.list-group-flush
  - giftings.each do |gifting|
    li.list-group-item.list-group-item-action
      i.fas.fa-gift>
      strong => gifting.gift.name
      => t('.for')
      strong => link_to gifting.recipient.title.downcase, root_path(recipient: gifting.recipient.title)
      => t('.on_occasion')
      strong => link_to gifting.occasion.name, root_path(occasion: gifting.occasion.name)
      - if defined?(edit) && edit
        => link_to t('edit'), edit_gift_path(gifting.gift)
      - if defined?(destroy) && destroy
        => link_to t('destroy'), gifting.gift, method: :delete, data: { confirm: 'Are you sure?' }

.mt-4
    = will_paginate giftings, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/gifts/edit.html.slim
h1 = t('.header')

= render 'form', gift: @gift

app/views/gifts/index.html.slim
/ header.text-white
/   .text-center
/     h1 Место, где есть все подарки
/     p.lead Выбирайте поводы для подарков и получателей, чтобы придумать свой подарок

.row.mt-4
  .col-3
    = render 'filters'
  .col-9
    = render 'list', giftings: @giftings

app/views/gifts/my.html.slim
h1 = t('.header')

= render 'list', giftings: @giftings, edit: true, destroy: true

app/views/gifts/new.html.slim
h1 = t('.header')

= render 'form', gift: @gift